{% set name = "azure-storage-blob" %}
{% set version = "12.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02030d657914c221961f6e7ebafc6ec36761649c04396b368e0b102cbcdcf26c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
   - python
   - azure-core <2.0.0,>=1.4.0
   - cryptography >=2.1.4
   - msrest >=0.6.10

test:
  imports:
    - azure.storage.blob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/azure-storage-blob/
  summary: Microsoft Azure Blob Storage Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
