travis:
  secure:
    BINSTAR_TOKEN: AS0Zg796Rh69ekuZFO3HwE0Ihr3fpBhKcLtPdGqGbP+orjCZ2vV07GdSve4c6RJPG+AcwPRqZw+es4a6zdweJt1UBqs08l6P7w8f3AsVZfugxuT61aG6e4NMwTIJ5K9pDTNxIiDn9EGJ9cIAun8VWeQTXaX2s9Wm2wH0YTb/T/v2vsQ8Bs14orObEn3A6bSfonFeb5Dc29Njv18r0TBKhAhecqa43PSOn4WhdSyhG8/zqrKdijAuWZrj5/vO11VnafYGuVxiPXNBHwRszToAEJ2Y3jlKIcIYj+rPJr1ypB9QUb3tslAc/sVxfh5hrsnc7SBV5jEJ0DlXRSQOkNKOlVMAalmzpnMKTMcxCVS7t+tKKd7NHTzPkU7LMJYzVIJTBbfPQiUm+CHzsdGVzT3PfdoeEeIJx3By15MPnxMHohRvYQ9Ckgxb/UXhpkRE/24p/BXgJABP0kof4IFDdcdSa9tXMdWmok9LMMTjzpTItqeSbPa/rCxU+Q4UdBmobJ35ZqcxBZ7Im1wOBWJeHzRC4K2vVl4C81dz4UEaUw38HSATWJ/05LlGVfK+rtYLQyZMSrG4Wwt9Ya1qhXyHlJsWB4CyHdHnJ7Ck/Pcu/29Copk6mkVOpbQHqD2pWRuUI4h8R+LPET67qQzajzmtpS/IqQvSNN+3uo9Ngx9t+ZNkj4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
