travis:
  secure:
    BINSTAR_TOKEN: mrrcyU7BtqCUIvpQHR0IrjDFl+VQLCgz5/6GdErx9RhaqSgHt1mtye1+rBJ4WEsWjVH756da9O6cdjNTHGk09CPb47fDu5Xmsca51F0UCKwFy0KSdbRP3z8WMuWb1hnEzOouwE0fWuSK5mj5NJSgv6C0/E496ECRtvZhR3mZTOqEFef2gskMpaMr8p+U9f3bYo5z0YSFoIKQTubOfVnmbt96/ipLGV/3Vfh36Nu9eUv/SG155aby+SGwoBJFEwiNp4OcteDe4fZw732qV8YrpEBUPLVUoaD2WDVwp0JkmsKjOo7p3BjEdF2wCmCgHnvFk/CTHcVZC+ph9+sapRhniavcsOGqyHW7ROPrZFzgMIZlZDxD/d0OBnvLnUvpa7+xR3AaHqPyPu52WyCzbBUq8b3mbDrpNcHYnOB3BLCR59BsheUKzKMKRyU8bB0l0vzqqcxBY6/rR/QBVd7VFnlEabFJJSuup3cie0yUlTB/BOWeXDPLW3PKef3esKoG2VY9TQs/p8WnbHIOR3e4HxlN3Y+/8pgPgRFZFqnSLa+1Tx1cdwsj7j0IDjeVum2HthZ8Ibv1D0rrKDQMfX5HV9ivSG33v0FqM7sXpYexTvdJJKyYv0Jih6gdJpGRaX1HHcx06m+guQFTAYVLxST1H7XRZ9A78MzXW6dHUzmGtB6YOYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
